# STATUS CODES
EXTERNAL_LOGIN_OK = 200
EXTERNAL_LOGIN_ERROR = 330
EXTERNAL_LOGIN_MISSING = 460
INTERNAL_ERROR_CODE = 10000

# REQUEST FIELDS
CLIENT_NAME_FIELD = 'clientName'
CLIENT_VERSION_FIELD = 'clientVersion'
DEV_ID_FIELD = 'devId'
FORMAT_FIELD = 'f'
ID_TYPE_FIELD = 'idType'
PASSWORD_FIELD = 'pwd'
LOGIN_FIELD = 's'